[tool.poetry]
name = "megabot"
version = "2.0.0"
description = ""
license = "MIT"
authors = ["jan <jan.meineke@mailbox.org>"]
readme = "README.md"
repository = "https://github.com/aurxl/MegaBot"

[tool.poetry.dependencies]
python = "^3.12"
discord = "*"
ffmpeg = "*"
mutagen = "*"
sympy = "*"
yt-dlp = "*"
pynacl = "*"
requests = "*"
pylint = "*"
pytest = "*"
pytest-cov = "*"
dynaconf = "^3.2.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
megabot = "megabot.main:main"
