[tool.poetry]
name = "megabot"
version = "0.1.0"
description = ""
authors = ["jan <jan.meineke@mailbox.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9.2"
discord = "^2.1.0"
ffmpeg = "^1.4"
mutagen = "^1.46.0"
sympy = "^1.11.1"
yt-dlp = "^2023.07.06"
pynacl = "^1.5.0"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
